/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `duplicate_tasks`;
CREATE TABLE IF NOT EXISTS `duplicate_tasks` (
  `Id` bigint(10) NOT NULL AUTO_INCREMENT,
  `DuplicateValue` varchar(1) NOT NULL,
  `RepeatEvery` int(11) NOT NULL DEFAULT 0,
  `Weekly_Su` int(11) DEFAULT NULL,
  `Weekly_Mo` int(11) DEFAULT NULL,
  `Weekly_Tu` int(11) DEFAULT NULL,
  `Weekly_We` int(11) DEFAULT NULL,
  `Weekly_Th` int(11) DEFAULT NULL,
  `Weekly_Fr` int(11) DEFAULT NULL,
  `Weekly_Sa` int(11) DEFAULT NULL,
  `Monthly_Day` int(11) DEFAULT NULL,
  `Yearly_Month` int(11) DEFAULT NULL,
  `Yearly_MonthDay` int(11) DEFAULT NULL,
  `EndAfter` int(11) NOT NULL DEFAULT 0,
  `EndOn` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
