/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `identity_users_rol`;
CREATE TABLE IF NOT EXISTS `identity_users_rol` (
  `Id` bigint(10) NOT NULL AUTO_INCREMENT,
  `IdfUser` bigint(10) NOT NULL,
  `IdfRol` bigint(10) NOT NULL,
  `State` varchar(1) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `_idx` (`IdfUser`),
  KEY `IdentityUsersRolIdfRol_Identity_Roles_Id_idx` (`IdfRol`),
  CONSTRAINT `IdentityUsersRolIdfRol_Identity_Roles_Id` FOREIGN KEY (`IdfRol`) REFERENCES `identity_roles` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `IdentityUsersRolIdfUser_Identity_Users_Id` FOREIGN KEY (`IdfUser`) REFERENCES `identity_users` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
