/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `project_assets`;
CREATE TABLE IF NOT EXISTS `project_assets` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `Amount` float NOT NULL,
  `TaxFed` int(11) DEFAULT NULL,
  `TaxProb` int(11) DEFAULT NULL,
  `Type` varchar(250) NOT NULL,
  `Description` varchar(1000) DEFAULT NULL,
  `Date` datetime NOT NULL,
  `ProjectId` bigint(20) NOT NULL,
  `Category` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
