/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `tasks_reminders`;
CREATE TABLE IF NOT EXISTS `tasks_reminders` (
  `Id` bigint(10) NOT NULL AUTO_INCREMENT,
  `IdfTask` bigint(10) NOT NULL,
  `IdfSettingReminderTime` bigint(10) NOT NULL,
  `State` varchar(2) NOT NULL DEFAULT 'C',
  `IdfPeriod` bigint(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  KEY `fk_tasks_reminders_tasks_idx` (`IdfTask`),
  KEY `fk_tasks_reminders_settingReminder_idx` (`IdfSettingReminderTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
