// Generated by https://quicktype.io

class Login {
  String id;
  String authToken;
  int expiresIn;

  Login({
    this.id,
    this.authToken,
    this.expiresIn,
  });
  // Login()
}
